// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsm_gPPILktbBNpNmgXkgXApIGLWJoNFc',
    appId: '1:876209393650:web:09e50ddc871c6c0bcca56b',
    messagingSenderId: '876209393650',
    projectId: 'gymappshubham',
    authDomain: 'gymappshubham.firebaseapp.com',
    storageBucket: 'gymappshubham.appspot.com',
    measurementId: 'G-0WLGJPQM5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ0MIbU6jYtTNscJ0rYVQJSF43hF7I7Ek',
    appId: '1:876209393650:android:d3877b83849383cdcca56b',
    messagingSenderId: '876209393650',
    projectId: 'gymappshubham',
    storageBucket: 'gymappshubham.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPwWAKwhsy6RQ5PrV-lSRvFYEh-GxlTgk',
    appId: '1:876209393650:ios:b1aeb1a2a8bc26d1cca56b',
    messagingSenderId: '876209393650',
    projectId: 'gymappshubham',
    storageBucket: 'gymappshubham.appspot.com',
    iosBundleId: 'com.example.gymappshubham',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPwWAKwhsy6RQ5PrV-lSRvFYEh-GxlTgk',
    appId: '1:876209393650:ios:9ea93ffac4e3709fcca56b',
    messagingSenderId: '876209393650',
    projectId: 'gymappshubham',
    storageBucket: 'gymappshubham.appspot.com',
    iosBundleId: 'com.example.gymappshubham.RunnerTests',
  );
}
